version: 0.2

env:
  secrets-manager:
    USERNAME: "com.amazonaws.ec2.madison.dockerhub.amazon-ecs-local-container-endpoints.credentials:username"
    PASSWORD: "com.amazonaws.ec2.madison.dockerhub.amazon-ecs-local-container-endpoints.credentials:password"

phases:
  pre_build:
    commands:
      - echo "Logging into DockerHub..."
      - docker login -u ${USERNAME} --password ${PASSWORD}
  build:
    # build and tag docker image. This will read ARCH_SUFFIX env var set in the
    # Codebuild project.
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - make build-image
      - make publish-dockerhub
